Controllers/ItemsController.cs
using BoutiqueManagement.IServices;
using BoutiqueManagement.Models;
using BoutiqueManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoutiqueManagement.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ItemsController : Controller
    {
        private IItemService _itemService;


        public ItemsController(IItemService itemService)
        {
            _itemService = itemService;
        }
        // GET: Items
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetData()
        {
            var result = _itemService.GetItems();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddItem()
        {
            var categories = _itemService.CategoryList();
            var brands = _itemService.BrandList();
            ItemViewModel itemViewModel = new ItemViewModel();
            itemViewModel.BrandList = brands;
            itemViewModel.CategoryList = categories;
            return View(itemViewModel   );
        }
        [HttpPost]
        public ActionResult AddItem(ItemViewModel itemViewModel)
        {
            Item item = new Item();
            item.ItemName = itemViewModel.ItemName;
            item.Price = itemViewModel.Price;
            item.CategoryId = itemViewModel.CategoryId;
            item.BrandId = itemViewModel.BrandId;
            var file = itemViewModel.file;
            if (file != null && file.ContentLength > 0)
            {
                string _FileName = Path.GetFileName(file.FileName);
                string ext = Path.GetExtension(file.FileName);
                _FileName = item.ItemName + ext;
                string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                file.SaveAs(_path);
                item.filePath = "~/UploadedFiles/"+_FileName;
                // item.ItemImage = itemViewModel.ItemImage;
            }
            
            int result=_itemService.AddItem(item);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data= _itemService.GetItemById(id);
            var categories = _itemService.CategoryList();
            var brands = _itemService.BrandList();
            ItemViewModel itemViewModel = new ItemViewModel();
            itemViewModel.BrandList = brands;
            itemViewModel.CategoryList = categories;
            itemViewModel.ItemId = data.ItemId;
            itemViewModel.ItemName = data.ItemName;
            itemViewModel.ItemImage = data.ItemImage;
            itemViewModel.Price = data.Price;
            itemViewModel.CategoryId=data.CategoryId;
            itemViewModel.BrandId = data.BrandId;
            string _path = data.filePath;
            ViewBag.filePath = _path;
            return View(itemViewModel);
        }
        [HttpPost]
        public ActionResult Edit(ItemViewModel itemViewModel)
        {
            Item item = new Item();
            item.ItemName = itemViewModel.ItemName;
            item.Price = itemViewModel.Price;
            item.CategoryId = itemViewModel.CategoryId;
            item.BrandId = itemViewModel.BrandId;
            item.ItemId = itemViewModel.ItemId;
            var file = itemViewModel.file;
            if (file!=null && file.ContentLength > 0)
            {
                string _FileName = Path.GetFileName(file.FileName);
                string ext= Path.GetExtension(file.FileName);
                _FileName = item.ItemName+ext;
                string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                file.SaveAs(_path);
                item.filePath = "~/UploadedFiles/" + _FileName;
               // item.ItemImage = itemViewModel.ItemImage;
            }
            int result = _itemService.UpdateItem(item);
            return RedirectToAction("Index");
        }
        public FileResult OpenFile(string fileName)
        {
            string fName = Path.GetFileName(fileName);
            try
            {
                return File(new FileStream(Server.MapPath("~/UploadedFiles/" + fName), FileMode.Open), "application/octetstream", fName);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public FileResult OpenFilePath(string filePath)
        {
            string fileName = Path.GetFileName(filePath);
           
            try
            {
                return File(new FileStream(filePath, FileMode.Open), "application/octetstream", fileName);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Controllers/LoginController.cs
using BoutiqueManagement.App_Start;
using IdentityManagement.DAL;
using IdentityManagement.Entities;
using IdentityManagement.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BoutiqueManagement.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Logout()
        {
            SignInManager.AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        // GET: Login
        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginInfo objLogin, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser oUser = await SignInManager.UserManager.FindByNameAsync(objLogin.UserName);
                if (oUser != null && oUser.Password == objLogin.Password)
                {
                    switch (oUser.Status)
                    {
                        case EnumUserStatus.Pending:
                            ModelState.AddModelError("", "Error: User account has not been verified.");
                            break;
                        case EnumUserStatus.Active:
                            SignInManager.SignIn(oUser, false, false);
                            IList<string> roleList = UserRoleController.GetUserRoles(oUser.Id);
                            foreach (string role in roleList)
                            {
                                UserManager.AddToRole(oUser.Id, role);
                            }

                            //if no return url provided then redirect page based on role
                            if (string.IsNullOrEmpty(returnUrl))
                            {
                                if (roleList.IndexOf("Administrator") >= 0)
                                {
                                    return RedirectToAction("Index", "Admin");
                                }
                                else
                                {
                                    return RedirectToAction("Index", "Member");
                                }
                            }
                            return RedirectToLocal(returnUrl);

                        case EnumUserStatus.Banned:
                            ModelState.AddModelError("", "Error: User account has been banned.");
                            break;
                        case EnumUserStatus.LockedOut:
                            ModelState.AddModelError("", "Error: User account has been locked out due to multiple login tries.");
                            break;
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Error: Invalid login details.");
                }
            }
            return View(objLogin);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/modernizr-2.8.3.js" type="text/javascript"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.7.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>
<body>
    <header class="row col-md-12 FullContent">
      
        <div class="d-block px-3 py-2 text-center text-bold text-white old-bv">
            @Html.Partial("_TopMenu")
        </div>
    </header>
    <div class="row col-md-12 FullContent">
        <div class="col-md-2 CustomLeftnavbar" style="background-color:gainsboro">
            @{Html.RenderPartial("~/Views/Shared/_LeftMenu.cshtml");}
        </div>
        <div class="container col-md-10" style="background-color:ivory">
            <main role="main" class="CustomBody">
                @RenderBody()
            </main>

        </div>
    </div>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>



</body>
</html>

Views/Shared/_MenuBar.cshtml
<nav class="navbar navbar-light bg-light">
    @Html.ActionLink("Diva Collection", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    <ul class="nav navbar-nav">
        <li>
            <span>@Html.ActionLink("Home", "Index", "Home")</span>
            <span>@Html.ActionLink("About", "Index", "About")</span>
            @if (IdentityManagement.Utilities.Utils.IfUserInRole("Member"))
            {
                <span>@Html.ActionLink("Member", "Index", "Member")</span>
            }
            else if (IdentityManagement.Utilities.Utils.IfUserInRole("Administrator"))
            {
                <span>@Html.ActionLink("Admin", "Index", "Admin")</span>
                <span>@Html.ActionLink("Item", "Index", "Items")</span>
            }

            @if (IdentityManagement.Utilities.Utils.IfUserAuthenticated())
            {
                <span>@Html.ActionLink("Logout", "Logout", "Login")</span>

            }
            else
            {

                <span>@Html.ActionLink("Login", "Index", "Login")</span>
            }
        </li>

    </ul>
</nav>

Views/Shared/_TopMenu.cshtml
<nav class="navbar navbar-light bg-light">
    @Html.ActionLink("Diva Collection", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    <ul class="nav navbar-nav">
        <li>
            <span>@Html.ActionLink("Home", "Index", "Home")</span>
            <span>@Html.ActionLink("About", "Index", "About")</span>
            @if (IdentityManagement.Utilities.Utils.IfUserInRole("Member"))
            {
                <span>@Html.ActionLink("Member", "Index", "Member")</span>
            }
            else if (IdentityManagement.Utilities.Utils.IfUserInRole("Administrator"))
            {
                <span>@Html.ActionLink("Admin", "Index", "Admin")</span>
                <span>@Html.ActionLink("Item", "Index", "Items")</span>
            }

            @if (IdentityManagement.Utilities.Utils.IfUserAuthenticated())
            {
                <span>@Html.ActionLink("Logout", "Logout", "Login")</span>

            }
            else
            {

                <span>@Html.ActionLink("Login", "Index", "Login")</span>
            }
        </li>

    </ul>
</nav>